# Generated by Django 6.0.4 on 2026-05-04 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefs', to='menu.location'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menu.chef'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='locations',
            field=models.ManyToManyField(related_name='menu_items', to='menu.location'),
        ),
    ]
